language: python
matrix:
  fast_finish: true
  include:
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.7"
      env: TOXENV=lint
    - python: "3.7"
      env: TOXENV=pylint
install: pip install tox
script: tox